language : node_js

node_js:
  - 12.18.1

cache:
  directories:
  - "node_modules"

script:
  - npm test

before_deploy:
  - npm install netlify-cli -g
  - CI= npm run build
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=build/ --prod
  on:
    branch: master